// app_data.dart
import './models/category.dart';
import './models/trip.dart';

const Categories_data = const [
  Category(
    id: 'c1',
    title: 'القدس',
    imageUrl: 'assets/image11.jpg',
    // 'https://images',
  ),
  Category(id: 'c2', title: 'بيت لحم', imageUrl: 'assets/batlaham.jpg'),
  Category(id: 'c3', title: 'رام الله', imageUrl: 'assets/ramallah.jpg'),
  Category(id: 'c4', title: 'نابلس', imageUrl: 'assets/nables.jpg'),
  Category(id: 'c5', title: 'أريحا', imageUrl: 'assets/areha.jpg'),
  Category(id: 'c6', title: 'الخليل', imageUrl: 'assets/alghlel.jpg'),
];

const Trips_data = const [
  Trip(
    id: 'm1',
    categories: [
      'c1',
    ],
    title: 'المسجد الأقصى - القدس',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl: 'assets/image12.jpg',
    duration: 20,
    activities: [
      'زيارة المسجد الأقصى',
      'الصلاة في الحرم القدسي الشريف',
      'جولة في ساحات المسجد',
      'زيارة قبة الصخرة',
      'التعرف على تاريخ المسجد الأقصى',
    ],
    program: [
      'زيارة صباحية للمسجد الأقصى وأداء الصلاة',
      'جولة مع مرشد في ساحات الحرم القدسي',
      'زيارة المصلى المرواني وقبة الصخرة',
      'وقت حر للتأمل والعبادة',
    ],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm2',
    categories: [
      'c1',
    ],
    title: 'البلدة القديمة وكنيسة القيامة - القدس',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl: 'assets/kanesaalgeama.jpg',
    duration: 10,
    activities: [
      'زيارة كنيسة القيامة',
      'المشي على طريق الآلام',
      'زيارة سوق القدس القديم',
      'تذوق المأكولات المقدسية التقليدية',
    ],
    program: [
      'بدء الجولة من باب العامود',
      'زيارة كنيسة القيامة والمواقع المسيحية المقدسة',
      'استكشاف الأسواق التاريخية في البلدة القديمة',
      'تناول الغداء في أحد المطاعم التقليدية',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm3',
    categories: [
      'c1',
    ],
    title: 'جبل الزيتون والقدس الشرقية - القدس',
    tripType: TripType.Recovery,
    season: Season.Winter,
    imageUrl: 'assets/gabalalzayton.jpg',
    duration: 45,
    activities: [
      'زيارة جبل الزيتون',
      'مشاهدة إطلالة بانورامية على القدس القديمة',
      'زيارة كنيسة الصعود',
      'استكشاف حديقة الجثمانية',
      'جولة في أحياء القدس الشرقية',
    ],
    program: [
      'صعود جبل الزيتون في الصباح الباكر',
      'زيارة المواقع الدينية على الجبل',
      'التقاط الصور البانورامية للمدينة القديمة',
      'استكشاف أحياء القدس الشرقية وثقافتها',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm4',
    categories: [
      'c2',
    ],
    title: 'كنيسة المهد - بيت لحم',
    tripType: TripType.Activities,
    season: Season.Spring,
    imageUrl: 'assets/kanesaalmahed.jpg',
    duration: 60,
    activities: [
      'زيارة كنيسة المهد',
      'التعرف على تاريخ مكان ولادة السيد المسيح',
      'حضور قداس (إن أمكن)',
      'زيارة مغارة الحليب',
      'التجول في ساحة المهد',
    ],
    program: [
      'زيارة صباحية لكنيسة المهد',
      'جولة مع مرشد داخل الكنيسة ومغارة الميلاد',
      'زيارة مغارة الحليب القريبة',
      'وقت حر في ساحة المهد',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm5',
    categories: [
      'c2',
    ],
    title: 'حقل الرعاة وبيت ساحور - بيت لحم',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/hagelalroah.jpg',
    duration: 15,
    activities: [
      'زيارة حقل الرعاة',
      'استكشاف كنيسة حقل الرعاة',
      'جولة في بيت ساحور',
      'شراء الحرف اليدوية التقليدية',
      'تذوق المأكولات المحلية',
    ],
    program: [
      'زيارة حقل الرعاة والكنيسة المجاورة',
      'جولة في بلدة بيت ساحور التاريخية',
      'زيارة ورش الحرف اليدوية التقليدية',
      'تناول الغداء في مطعم محلي',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm7',
    categories: [
      'c3',
    ],
    title: 'وسط مدينة رام الله الثقافي',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl: 'assets/wasatramallha.jpg',
    duration: 20,
    activities: [
      'زيارة المتحف الفلسطيني',
      'جولة في شارع ركب',
      'زيارة دار زهران للتراث والفنون',
      'استكشاف المقاهي والمطاعم العصرية',
      'التسوق في الأسواق المحلية',
    ],
    program: [
      'بدء اليوم بزيارة المتحف الفلسطيني',
      'جولة في وسط المدينة وشارع ركب',
      'زيارة المعارض الفنية والثقافية',
      'تناول الغداء في أحد المطاعم العصرية',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm8',
    categories: [
      'c3',
    ],
    title: 'الحياة الليلية في رام الله',
    tripType: TripType.Recovery,
    season: Season.Spring,
    imageUrl: 'assets/ralmalahlele.jpg',
    duration: 35,
    activities: [
      'زيارة المقاهي والحانات العصرية',
      'حضور عرض موسيقي حي',
      'تجربة المطبخ الفلسطيني الحديث',
      'التسوق في المراكز التجارية الحديثة',
      'الاستمتاع بأجواء المدينة الليلية',
    ],
    program: [
      'بدء المساء بتناول العشاء في مطعم عصري',
      'زيارة الحانات والمقاهي الشهيرة',
      'حضور عرض موسيقي أو ثقافي',
      'الاستمتاع بالأجواء الليلية في وسط المدينة',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm10',
    categories: [
      'c4',
    ],
    title: 'البلدة القديمة والحمامات التركية - نابلس',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/hamamaltorky.jpg',
    duration: 30,
    activities: [
      'جولة في البلدة القديمة',
      'زيارة الحمامات التركية التاريخية',
      'استكشاف المساجد والكنائس القديمة',
      'التسوق في الأسواق التقليدية',
      'تذوق الكنافة النابلسية الشهيرة',
    ],
    program: [
      'بدء اليوم بجولة في البلدة القديمة',
      'زيارة الحمامات التركية واختبار تجربة الاستحمام التقليدية',
      'استكشاف المعالم الدينية والتاريخية',
      'تناول الكنافة في أشهر محلاتها',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm11',
    categories: [
      'c4',
    ],
    title: 'جبل جرزيم والسامريون - نابلس',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/gabalgrezem.jpg',
    duration: 30,
    activities: [
      'صعود جبل جرزيم',
      'زيارة المجتمع السامري',
      'مشاهدة إطلالة بانورامية على نابلس',
      'التعرف على التاريخ السامري',
      'المشي في الطبيعة الخلابة',
    ],
    program: [
      'رحلة صباحية إلى جبل جرزيم',
      'لقاء مع المجتمع السامري والتعرف على ثقافتهم',
      'نزهة في الطبيعة والتقاط الصور البانورامية',
      'العودة إلى المدينة وتناول الغداء التقليدي',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm13',
    categories: [
      'c5',
    ],
    title: 'المواقع الأثرية في أريحا',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/alkanan.jpg',
    duration: 30,
    activities: [
      'زيارة تل السلطان (أريحا القديمة)',
      'استكشاف قصر هشام الأموي',
      'زيارة دير القرنطل',
      'جولة في متحف أريحا',
      'مشاهدة شجرة الجميز التاريخية',
    ],
    program: [
      'بدء اليوم بزيارة تل السلطان والتعرف على تاريخ أقدم مدينة في العالم',
      'استكشاف قصر هشام الأموي وفسيفسائه الرائعة',
      'صعود التلفريك إلى دير القرنطل',
      'زيارة متحف أريحا في فترة ما بعد الظهر',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm14',
    categories: [
      'c5',
    ],
    title: 'الاستجمام في البحر الميت - أريحا',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/baharalmaeat.jpg',
    duration: 30,
    activities: [
      'السباحة والتعويم في البحر الميت',
      'التدليك بالطين الطبيعي',
      'الاسترخاء على الشاطئ',
      'زيارة المنتجعات الصحية',
      'مشاهدة غروب الشمس على البحر الميت',
    ],
    program: [
      'قضاء الصباح في التعويم والاستمتاع بمياه البحر الميت',
      'جلسة تدليك بالطين الطبيعي',
      'الاسترخاء والغداء في أحد المنتجعات',
      'الاستمتاع بغروب الشمس الخلاب',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm16',
    categories: [
      'c6',
    ],
    title: 'الحرم الإبراهيمي والبلدة القديمة - الخليل',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/alharamalalbraheme.jpg',
    duration: 30,
    activities: [
      'زيارة الحرم الإبراهيمي الشريف',
      'جولة في البلدة القديمة',
      'زيارة سوق الخليل القديم',
      'مشاهدة صناعة الزجاج والخزف التقليدية',
      'تذوق المأكولات الخليلية الشهيرة',
    ],
    program: [
      'بدء اليوم بزيارة الحرم الإبراهيمي والتعرف على تاريخه',
      'جولة في البلدة القديمة وزيارة سوق الخليل',
      'مشاهدة الحرف التقليدية مثل صناعة الزجاج والخزف',
      'تذوق الأطعمة المحلية في أحد المطاعم التقليدية',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm17',
    categories: ['c6'],
    title: 'جولة في مزارع العنب وزيارة معاصر العنب التقليدية - الخليل',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'assets/alanab.jpg',
    duration: 30,
    activities: [
      'زيارة مزارع العنب في الخليل',
      'التعرف على طرق الزراعة والري التقليدية',
      'مشاهدة عملية حصاد العنب وتذوقه مباشرة من الشجرة',
      'زيارة معاصر العنب التقليدية والتعرف على عملية تحويل العنب إلى منتجات مثل الدبس والخل',
      'تذوق منتجات العنب المحلية وتعلم كيفية تحضيرها',
    ],
    program: [
      'بدء اليوم بجولة في مزارع العنب ومشاهدة عملية الحصاد',
      'زيارة معاصر العنب التقليدية والتعرف على عملية الإنتاج',
      'تجربة تذوق منتجات العنب المحلية والمشاركة في تحضير بعض منها',
      'شراء المنتجات المحلية والعودة',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
];
